# Generated by Django 3.2.17 on 2023-02-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20230218_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='carousel_image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='carousel_image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='show',
            name='carousel_image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
