# Generated by Django 3.2.17 on 2023-03-02 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20230302_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='character',
        ),
    ]
