# Generated by Django 3.2.17 on 2023-03-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_remove_movie_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cast',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='writer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='cast',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='writer',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
