# Generated by Django 3.2.17 on 2023-03-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20230302_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='synopsis',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
