# Generated by Django 3.2.17 on 2023-03-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_alter_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
