# Generated by Django 3.2.17 on 2023-03-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='media_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='media_type',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
