# Generated by Django 3.2.17 on 2023-03-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_auto_20230321_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='game',
        ),
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='review',
            name='show',
        ),
    ]
