# Generated by Django 3.2.17 on 2023-03-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_auto_20230324_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='synopsis',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='synopsis',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
